apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  namespace: observability

data:
  config.yaml: |
    auth_enabled: false

    server:
      http_listen_port: 3100

    common:
      path_prefix: /loki

      storage:
        filesystem:
          chunks_directory: /loki/chunks
          rules_directory: /loki/rules

      replication_factor: 1

      ring:
        instance_addr: 127.0.0.1
        kvstore:
          store: inmemory

    schema_config:
      configs:
        - from: 2024-01-01
          store: boltdb-shipper
          object_store: filesystem
          schema: v13
          index:
            prefix: index_
            period: 24h

    storage_config:
      boltdb_shipper:
        active_index_directory: /loki/index
        cache_location: /loki/cache

      filesystem:
        directory: /loki/chunks
