apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
  namespace: observability

data:
  config.yaml: |
    server:
      http_listen_port: 9080

    positions:
      filename: /tmp/positions.yaml

    clients:
      - url: http://loki:3100/loki/api/v1/push

    scrape_configs:
      - job_name: kubernetes-pods

        kubernetes_sd_configs:
          - role: pod

        pipeline_stages:
          - docker: {}

        relabel_configs:
          - source_labels:
              - __meta_kubernetes_pod_name
            target_label: pod
