apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: observability

data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:

    exporters:
      prometheus:
        endpoint: "0.0.0.0:8889"

      logging:
        verbosity: detailed

    service:
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [logging]

        metrics:
          receivers: [otlp]
          exporters: [prometheus]
