apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  namespace: observability

spec:
  replicas: 1

  selector:
    matchLabels:
      app: otel-collector

  template:
    metadata:
      labels:
        app: otel-collector

    spec:
      containers:
        - name: otel-collector
          image: otel/opentelemetry-collector-contrib:latest

          args:
            - "--config=/etc/otelcol-contrib/config.yaml"

          ports:
            - containerPort: 4317

            - containerPort: 4318

            - containerPort: 8889

          volumeMounts:
            - name: config
              mountPath: /etc/otelcol-contrib

      volumes:
        - name: config
          configMap:
            name: otel-collector-config

---
apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: observability

spec:
  type: NodePort

  selector:
    app: otel-collector

  ports:
    - name: grpc
      port: 4317
      targetPort: 4317
      nodePort: 30417

    - name: http
      port: 4318
      targetPort: 4318
      nodePort: 30418

    - name: metrics
      port: 8889
      targetPort: 8889
