apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-monitor
  namespace: observability
spec:
  selector:
    matchLabels:
      app: backend

  namespaceSelector:
    matchNames:
      - skillpulse

  endpoints:
    - port: http
      path: /metrics
      interval: 15s
