name: CD

on:
  workflow_run:
    workflows:
      - CI
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: production

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1

        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            set -e

            APP_DIR="$HOME/github-actions-kubernetes-masterclass"
            BRANCH="main"

            # Clone repo if missing
            if [ ! -d "$APP_DIR" ]; then
              git clone -b $BRANCH \
              https://github.com/${{ github.repository }}.git \
              $APP_DIR
            fi

            cd $APP_DIR

            # Update latest code
            git fetch origin
            git checkout $BRANCH
            git reset --hard origin/$BRANCH

            # # Create .env file
            # printf "%s\n" \
            # "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" \
            # "DB_HOST=${{ secrets.DB_HOST }}" \
            # "DB_PORT=${{ secrets.DB_PORT }}" \
            # "DB_USER=${{ secrets.DB_USER }}" \
            # "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" \
            # "DB_NAME=${{ secrets.DB_NAME }}" \
            # > .env

            # Restart application
            # kind create cluster --config k8s/kind-config.yaml --name skillpulse
            # Restart application
            CLUSTER_NAME="skillpulse"
            
            # Create cluster only if it does not exist
            if ! kind get clusters | grep -q "^${CLUSTER_NAME}$"; then
              echo "Creating kind cluster: ${CLUSTER_NAME}"
              kind create cluster --config k8s/kind-config.yaml --name ${CLUSTER_NAME}
            else
              echo "Kind cluster already exists: ${CLUSTER_NAME}"
            fi
            
            # Ensure kubectl uses correct context
            kubectl cluster-info
            
                        kubectl apply -f k8s/00-namespace.yaml \
                          -f k8s/10-mysql.yaml \
                          -f k8s/20-backend.yaml \
                          -f k8s/30-frontend.yaml
                        kind get clusters
                        kubectl get pods -n skillpulse 
                        kubectl apply -f observability/k8s/
                        kubectl get pods -n observability

            # Show containers
            docker ps
